import { TreeViewProps } from "..";

export const STORYBOOK_TREE_VIEW_DATA: TreeViewProps["data"] = [
  {
    id: "languages",
    label: "Languages",
    checked: false,
    disabled: false,
    indeterminate: false,
    childrenNodes: [
      {
        id: "languages-front-end",
        label: "Front-end",
        parentId: "languages",
        checked: false,
        disabled: false,
        indeterminate: false,
        childrenNodes: [
          {
            id: "typescript",
            label: "TypeScript",
            parentId: "languages-front-end",
            checked: false,
            disabled: false,
            indeterminate: false,
          },
          {
            id: "javascript",
            label: "JavaScript",
            parentId: "languages-front-end",
            checked: false,
            disabled: false,
            indeterminate: false,
          },
        ],
      },
      {
        id: "languages-back-end",
        label: "Back-end",
        parentId: "languages",
        checked: false,
        disabled: false,
        indeterminate: false,
        childrenNodes: [
          {
            id: "python",
            label: "Python",
            parentId: "languages-back-end",
            checked: false,
            disabled: false,
            indeterminate: false,
          },
          {
            id: "ruby",
            label: "Ruby",
            parentId: "languages-back-end",
            checked: false,
            disabled: false,
            indeterminate: false,
          },
        ],
      },
    ],
  },
  {
    id: "frameworks",
    label: "Frameworks and Libraries",
    checked: false,
    disabled: false,
    indeterminate: false,
    childrenNodes: [
      {
        id: "frameworks-front-end",
        label: "Front-end",
        parentId: "frameworks",
        checked: false,
        disabled: false,
        indeterminate: false,
        childrenNodes: [
          {
            id: "react",
            label: "React",
            parentId: "frameworks-front-end",
            checked: false,
            disabled: false,
            indeterminate: false,
          },
          {
            id: "vue",
            label: "Vue.js",
            parentId: "frameworks-front-end",
            checked: false,
            disabled: false,
            indeterminate: false,
          },
        ],
      },
      {
        id: "frameworks-back-end",
        label: "Back-end",
        parentId: "frameworks",
        checked: false,
        disabled: false,
        indeterminate: false,
        childrenNodes: [
          {
            id: "flask",
            label: "Flask",
            parentId: "frameworks-back-end",
            checked: false,
            disabled: false,
            indeterminate: false,
          },
          {
            id: "rails",
            label: "Rails",
            parentId: "frameworks-back-end",
            checked: false,
            disabled: false,
            indeterminate: false,
          },
        ],
      },
    ],
  },
];
